spring:
  # 性能分析插件需要得数据源不同，用作测试环境
  datasource:
    url: jdbc:p6spy:mysql:///SchoolShop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver


  # 控制台输出，如果配置了日志控制台输出就为日志配置
  output:
    ansi:
      enabled: ALWAYS

mybatis-plus:
  # 打开日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置策略
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
