spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  redis:
    database: 0
    host: 1.14.109.156
    port: 6379
    password:
    timeout: 1500
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE  #加上这个就可以获取到HttpServletRequest
          thread:
            timeoutInMilliseconds: 10000

  #配置rabbitMq 服务器
  rabbitmq:
    host: 1.14.109.156
      port: 5672
        username: guest
          password: guest
          #虚拟host 可以不设置,使用server默认host
          virtual-host: TanLong