server:
  port: 9527


spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':  #匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id:  goods
          uri: http://localhost:9528
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/